### ISSUE TITLE
type error - list indices must be integers or slices, not float

### ISSUE THREAD

**Issue by GeraldSchmaussIMP** [russwong89/sharpness_detection_autofocus#2]
On running _cubic_spline.py_ in spyder 4.1.5. (python 3.8), an error comes up at line 53 A[row_count][4*row_count/2] = x[row_count/2]**3

_TypeError: list indices must be integers or slices, not float_

Checking the variable row_count just before that line states, that it is type int.
Which would mean that the type is changed within that line, causing the error.
I am quite new to coding, so I might be missing something obvious, but at this point I can’t make that bit of code run successfully.

**Comment by russwong89** [comment]
Hello!

As a disclaimer, this repository is no longer being maintained and was merely used for a project submission in a university course.

That being said, a simple way around this would be to just cast the indices to int, e.g.
`A[int(row_count)][int(4*row_count/2)] = x[int(row_count/2)]**3`

The reason why you're running into this error is likely because we used Python 2 for our course whereas you are using Python 3.
